version: '3.11'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    environment:
      - DJANGO_DB_USER=$DB_USER
      - DJANGO_DB_PASSWORD=$DB_PASSWORD
      - DJANGO_DB_HOST=$DB_HOST
      - DJANGO_DB_PORT=$DB_PORT
      - DJANGO_DB_NAME=$DB_NAME

    volumes:
      - .:/app
      - static_volume:/home/user/PyCharmProjects/Freshshop/static
      - media_volume:/home/user/PyCharmProjects/Freshshop/media
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST=$DB_HOST
      - POSTGRES_PORT=$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379

  celery:
    build: .
    command: celery -A Freshshop worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    mem_limit: 2g


volumes:
  static_volume:
  media_volume:
  postgres_data:
  redis_data: