# Generated by Django 4.2.5 on 2024-02-01 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subscriber_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stock'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='is_stock',
            field=models.BooleanField(default=False),
        ),
    ]
