# Generated by Django 4.2.5 on 2024-02-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_stock_product_product_stock_wishlist_is_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='count',
        ),
    ]
